package Login;  // Your package name

/**
 *
 * @author Administrator
 */
public class Loginform extends javax.swing.JPanel {

    // Declare components
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JPasswordField passwordField;

    /**
     * Creates new form Loginform
     */
    public Loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // Initialize components
        usernameLabel = new javax.swing.JLabel("Username:");
        passwordLabel = new javax.swing.JLabel("Password:");
        usernameField = new javax.swing.JTextField(20);
        passwordField = new javax.swing.JPasswordField(20);
        loginButton = new javax.swing.JButton("Login");

        // Set layout manager for the panel
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);

        // Horizontal layout setup
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50) // Add some padding
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameField)
                    .addComponent(passwordField)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        // Vertical layout setup
        layout.setVerticalGroup(
            layout.createSequentialGroup()
                .addGap(50, 50, 50)  // Add some padding
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField))
                .addGap(30, 30, 30)
                .addComponent(loginButton)
                .addContainerGap(50, Short.MAX_VALUE)
        );

        // Add action listener for the login button
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
    } 

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String username = usernameField.getText();
        char[] password = passwordField.getPassword();
        // Example validation (can be replaced with your actual logic)
        if (username.equals("admin") && new String(password).equals("admin123")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login Successful!");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Credentials. Try Again.");
        }
    }

    // End of variables declaration
}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
